apiVersion: v2
dependencies:
  - condition: eck-elasticsearch.enabled
    name: eck-elasticsearch
    repository: https://helm.elastic.co
    version: 0.12.1
  - condition: eck-kibana.enabled
    name: eck-kibana
    repository: https://helm.elastic.co
    version: 0.12.1
  - condition: eck-agent.enabled
    name: eck-agent
    repository: https://helm.elastic.co
    version: 0.12.1
  - condition: eck-fleet-server.enabled
    name: eck-fleet-server
    repository: https://helm.elastic.co
    version: 0.12.1
  - condition: eck-beats.enabled
    name: eck-beats
    repository: https://helm.elastic.co
    version: 0.12.1
  - condition: eck-logstash.enabled
    name: eck-logstash
    repository: https://helm.elastic.co
    version: 0.12.1
  - condition: eck-apm-server.enabled
    name: eck-apm-server
    repository: https://helm.elastic.co
    version: 0.12.1
  - condition: eck-enterprise-search.enabled
    name: eck-enterprise-search
    repository: https://helm.elastic.co
    version: 0.12.1
description: Elastic Stack managed by the ECK Operator
# kubeVersion: ">= 1.21.0-0"
name: eck-stack
type: application
version: 0.12.1
