apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv
spec:
  capacity:
    storage: 7Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-plex-media
  nfs:
    server: 192.168.1.3
    path: /mnt/plex-media/volume-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: plex
spec:
  storageClassName: nfs-plex-media
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 7Ti
  volumeName: plex-pv