---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent-gluetun.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "qbittorrent-gluetun.name" . }}
    chart: {{ include "qbittorrent-gluetun.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
  selector:
    matchLabels:
      app: {{ include "qbittorrent-gluetun.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "qbittorrent-gluetun.name" . }}
        release: {{ .Release.Name }}
    spec:
    # TODO: mount a configmap to the region.env file and then pass it into the main container as an env var instead of using an init container to write it to a shared volume
      # initContainers:
      #   - name: pick-region
      #     image: alpine:3.18
      #     command:
      #       - /bin/sh
      #       - -c
      #       - |
      #         REGION=$(printf '{{- range .Values.serverRegions }}{{ . }}\n{{- end }}' | awk 'BEGIN{srand()} {a[NR]=$0} END{print a[int(rand()*NR)+1]}')
      #         echo "SERVER_REGIONS='$REGION'" > /region/region.env
      #         cat /region/region.env
      #     securityContext:
      #       runAsNonRoot: false
      #       runAsUser: 0
      #     volumeMounts:
      #       - name: region
      #         mountPath: /region
      containers:
        - name: gluetun
          image: "{{ .Values.gluetun.image.repository }}:{{ .Values.gluetun.image.tag }}"
          imagePullPolicy: {{ .Values.gluetun.image.pullPolicy }}
          env:
          {{- range $k, $v := .Values.gluetun.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openvpn.secretName | quote }}
                  key: {{ .Values.openvpn.usernameKey | quote }}
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openvpn.secretName | quote }}
                  key: {{ .Values.openvpn.passwordKey | quote }}
            {{- if .Values.gluetun.serverRegions }}
            - name: SERVER_REGIONS
              value: {{ .Values.gluetun.serverRegions | quote }}
            {{- else if .Values.serverRegions }}
            - name: SERVER_REGIONS
              value: {{ join "," .Values.serverRegions | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.gluetun.securityContext | nindent 12 }}
          volumeMounts:
            - name: plex-media
              mountPath: {{ .Values.persistence.gluetun.mountPath }}
              subPath: {{ .Values.persistence.gluetun.subPath }}
          resources:
            {{- toYaml .Values.gluetun.resources | nindent 12 }}
        - name: qbittorrent
          image: "{{ .Values.qbittorrent.image.repository }}:{{ .Values.qbittorrent.image.tag }}"
          imagePullPolicy: {{ .Values.qbittorrent.image.pullPolicy }}
          env:
          {{- range $k, $v := .Values.qbittorrent.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
            - name: WEBUI_PORT
              value: {{ .Values.qbittorrent.webuiPort | quote }}
          ports:
            - containerPort: {{ .Values.qbittorrent.webuiPort }}
          resources:
            {{- toYaml .Values.qbittorrent.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.qbittorrent.securityContext | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.qbittorrent.startupProbe | nindent 12 }}
            tcpSocket:
              port: {{ .Values.qbittorrent.webuiPort }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  endpoint="http://localhost:{{ .Values.qbittorrent.webuiPort }}/api/v2/torrents/info?filter=stalled_downloading"
                  response=$(curl -s -o /dev/null -w "%{http_code}" "$endpoint")
                  body=$(curl -s "$endpoint")
                  if [ "$response" -eq 200 ] && [ "$(echo "$body" | jq -e '. | length == 0')" = "true" ]; then
                    exit 0
                  else
                    exit 1
                  fi
            initialDelaySeconds: {{ .Values.qbittorrent.livenessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.qbittorrent.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.qbittorrent.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.qbittorrent.livenessProbe.timeoutSeconds }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.qbittorrent.config.mountPath }}
              name: plex-media
              subPath: {{ .Values.persistence.qbittorrent.config.subPath }}
            - mountPath: {{ .Values.persistence.qbittorrent.downloads.mountPath }}
              name: plex-media
              subPath: {{ .Values.persistence.qbittorrent.downloads.subPath }}
      dnsPolicy: {{ .Values.deployment.dnsPolicy }}
      hostNetwork: {{ .Values.deployment.hostNetwork }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      volumes:
        - name: plex-media
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}
        # - name: region
        #   emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
