---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "qbittorrent-gluetun.fullname" . }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "qbittorrent-gluetun.name" . }}
    chart: {{ include "qbittorrent-gluetun.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "qbittorrent-gluetun.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
