---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-gluetun
  namespace: plex
  labels:
    app: qbittorrent-gluetun
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent-gluetun
  template:
    metadata:
      labels:
        app: qbittorrent-gluetun
    spec:
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun
          imagePullPolicy: Always
          env:
            - name: TZ
              value: UTC
            - name: VPN_SERVICE_PROVIDER
              value: surfshark
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: "openvpn"
                  key: "username"
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "openvpn"
                  key: "password"
            - name: FIREWALL_DEBUG
              value: "on"
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "16793,6881"
            # - name: DOT
            #   value: "off"
            # - name: DNS_KEEP_NAMESERVER
            #   value: "on"
            - name: UPDATER_PERIOD
              value: 20m
            - name: SERVER_COUNTRIES
              value: "United States"
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - name: gluetun-longhorn
              mountPath: /gluetun
          resources:
            requests:
              memory: 200Mi
              cpu: "0.1"
            limits:
              memory: 500Mi
              cpu: "0.5"
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
            - name: TZ
              value: "Etc/UTC"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 200Mi
              cpu: "0.1"
            limits:
              memory: 500Mi
              cpu: "0.5"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
          startupProbe:
            failureThreshold: 10
            periodSeconds: 10
            tcpSocket:
              port: 8080
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-longhorn
            - mountPath: /downloads
              name: plex-media
              subPath: media
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gluetun-longhorn
          persistentVolumeClaim:
            claimName: gluetun-longhorn
        - name: qbittorrent-longhorn
          persistentVolumeClaim:
            claimName: qbittorrent-longhorn
            readOnly: false
        - name: plex-media
          persistentVolumeClaim:
            claimName: "plex-pvc"
