## media.radarr.values.yml
replicaCount: 1

image:
  repository: "linuxserver/radarr"
  tag: "arm32v7-latest" # ARM image
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "65534"
  - name: PGID
    value: "65534"

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: radarr.palacpl.us
    external-dns.alpha.kubernetes.io/ttl: "120" #optional
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  pathType: Prefix
  hosts:
    - host: radarr.palacpl.us
      path: "/"
  tls:
    enabled: true
    secretName: secure-tls

volumes:
  - name: plex-pvc
    persistentVolumeClaim:
      claimName: plex-pvc # PersistentVolumeClaim created earlier

volumeMounts:
  - name: plex-pvc
    mountPath: "/config"
    subPath: Radarr
  - name: plex-pvc
    mountPath: "/downloads"
    subPath: media # Path /mnt/ssd/media/downloads/transmission where radarr picks up downloaded movies
  - name: plex-pvc
    mountPath: "/movies"
    subPath: "library/movies" # Path /mnt/ssd/media/library/movies where radarr moves and renames the movies

resources:
  requests:
    memory: 150Mi
    cpu: 0.1
  limits:
    memory: 1Gi
    cpu: 0.5
