global:
  domain: argocd.palacpl.us
  logging:
    level: info

configs:
  params:
    server.insecure: true

server:
  service:
    type: LoadBalancer

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: argocd.palacpl.us
      external-dns.alpha.kubernetes.io/ttl: "120" #optional
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    extraTls:
      - hosts:
        - argocd.palacpl.us
        # Based on the ingress controller used secret might be optional
        secretName: secure-tls