## media.transmission-openvpn.values.yml
replicaCount: 1

image:
  repository: haugene/transmission-openvpn
  tag: latest
  pullPolicy: IfNotPresent

dnsPolicy: "None"

dnsConfig:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4

env:
  - name: OPENVPN_PROVIDER
    value: "SURFSHARK" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
  - name: OPENVPN_CONFIG
    value: "us-chi.prod.surfshark.com_udp"
  # - name: OPENVPN_CONFIG
  #   value: "us-dtw.prod.surfshark.com_tcp"
  # - name: OPENVPN_PROTOCOL
  #   value: tcp
  # - name: OPENVPN_CONNECTION
  #   value: multihop
  # - name: OPENVPN_COUNTRY
  #   value: us
  # - name: OPENVPN_CITY
  #   value: any-city
  - name: OPENVPN_OPTS
    value: "--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings"
  - name: OPENVPN_USERNAME
    valueFrom:
      secretKeyRef:
        name: "openvpn"
        key: "username"
  - name: OPENVPN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "openvpn"
        key: "password"
  - name: LOCAL_NETWORK
    value: "192.168.0.0/24"
  - name: TRANSMISSION_PEER_PORT
    value: "47444"
  - name: TRANSMISSION_DOWNLOAD_DIR
    value: "/downloads/transmission"
  - name: TZ
    value: UTC
  - name: PUID
    value: "65534" #nobody
  - name: PGID
    value: "65534" #nogroup

service:
  type: ClusterIP
  port: 80

volumes:
  - name: media
    persistentVolumeClaim:
      claimName: "plex-pvc"
  - name: config
    persistentVolumeClaim:
      claimName: "transmission-config-pvc"

volumeMounts:
  - name: media
    mountPath: "/data"
    subPath: transmission-data
  - name: config
    mountPath: "/config/transmission-home"
    subPath: transmission-home
  - name: media
    mountPath: "/downloads/transmission"
    subPath: media

securityContext:
  capabilities:
    add:
      - NET_ADMIN

podSecurityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
