apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluetun-config-pv
  namespace: plexserver
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/gluetun"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-config-pvc
  namespace: plexserver
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
  namespace: plexserver
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/qbittorrent"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: plexserver
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
