apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config-pv
  namespace: plex
  labels:
    type: local
spec:
  storageClassName: radarr-config
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/radarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: plex
spec:
  storageClassName: radarr-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
