# https://metallb.universe.tf/configuration/
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - metallb-address-pool