apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  source:
    path: plex/jackett
    repoURL: https://github.com/mike-palacio-nice/kubernetes-deployment.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true