apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-backup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mike-palacio-nice/kubernetes-deployment.git
    targetRevision: HEAD
    path: plex/s3-backup
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
