apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: screenplay
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  source:
    path: helm/screen-play
    repoURL: https://github.com/palacplus/screen-play.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  retry:
    limit: 5
    backoff:
      duration: 10s
      maxDuration: 5m
      factor: 2
