apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seer
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/seerr-team/seerr
      chart: seerr-chart
      targetRevision: "3.4.2"
      helm:
        valueFiles:
          - $values/plex/seer/values.yaml
    - repoURL: https://github.com/mike-palacio-nice/kubernetes-deployment.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
