apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secure
spec:
  secretName: secure-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - palacpl.us
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.palacpl.us"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer