apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-config-pv
  namespace: plexserver
  labels:
    type: local
spec:
  storageClassName: jackett-config
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/jackett"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config-pvc
  namespace: plexserver
spec:
  storageClassName: jackett-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
