apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3
  mountOptions:
    - allow-other
    - uid=65534
    - gid=65534
    - allow-delete
    - allow-overwrite
    - region us-west-2
    - aws-max-attempts 5 # Configure number of retries for S3 requests
    - debug
  csi:
    driver: s3.csi.aws.com
    volumeHandle: palacplus-homeserver
    volumeAttributes:
      bucketName: palacplus-homeserver
      mountOptions: "--dir-mode=0777 --file-mode=0666"
