apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
  namespace: plexserver
  labels:
    type: local
spec:
  storageClassName: plex-config
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/plex"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: plexserver
spec:
  storageClassName: plex-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi