apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
  labels:
    type: local
spec:
  storageClassName: plex-config
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/plex"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  storageClassName: plex-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi