apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
  namespace: plexserver
spec:
  storageClassName: ""
  volumeMode: Filesystem 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: plexserver
spec:
  storageClassName: ""
  volumeName: plex-config-pv
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi  