apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: plex
spec:
  storageClassName: nfs-plex-media
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 2Ti
  volumeName: volume-1