apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: plexserver
spec:
  storageClassName: nfs-config-sc
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Gi
