apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: plexserver
spec:
  storageClassName: plex-nfs
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 2Ti
