apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-cephfs
  namespace: plex
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: rook-cephfs
