apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv
  namespace: plex
  labels:
    type: local
spec:
  storageClassName: transmission-config
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/transmission"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
  namespace: plex
spec:
  storageClassName: transmission-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
